<?php
/**
 * @file
 *
 * Implements back end support for splitting a paragraph into multiple
 * paragraphs.
 */

/**
 * Implements hook_views_api().
 */
function paragraphs_extra_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function paragraphs_extra_menu() {
  $info = array();
  $info['ajax/paragraphs-extra/%ctools_js/bundle-select/%'] = array(
    'title' => t('Insert'),
    'page callback' => 'paragraphs_extra_bundle_info_select_page',
    'page arguments' => array(2, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'paragraphs_extra.bundle_info.inc',
    'file path' => drupal_get_path('module', 'paragraphs_extra') . '/includes',
  );
  return $info;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function paragraphs_extra_field_widget_form_alter(&$element, &$form_state, $context) {
  $wrapper_id = paragraphs_extra_get_widget_wrapper_id($element, $context);
  if ($wrapper_id) {
    $element['#attached']['js'][] = drupal_get_path('module', 'paragraphs_extra') . '/js/ParagraphsExtra.js';

    paragraphs_extra_include('ajax_api');
    paragraphs_extra_ajax_api_attach($wrapper_id, $element, $context);

    paragraphs_extra_include('bundle_info');
    paragraphs_extra_bundle_info_modal_attach($element, $context);

    paragraphs_extra_include('pretty_paragraphs');
    paragraphs_extra_pretty_paragraphs_attach($wrapper_id, $element, $form_state, $context);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function paragraphs_extra_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if ($form['#field']['type'] == 'paragraphs') {
    paragraphs_extra_include('pretty_paragraphs');
    paragraphs_extra_pretty_paragraphs_attach_instance_settings($form, $form_state);
  }
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function paragraphs_extra_form_paragraphs_admin_bundle_form_alter(&$form, &$form_state) {
  paragraphs_extra_include('bundle_info');
  paragraphs_extra_bundle_info_form_attach($form, $form_state);
}

function paragraphs_extra_bundle_info_form_submit($form, &$form_state) {
  paragraphs_extra_include('bundle_info');
  paragraphs_extra_bundle_info_handle_form_submit($form, $form_state);
}

/**
 * Handles ajax for splitting apart paragraph to insert a new paragraph item.
 */
function paragraphs_extra_ajax_api_command_submit($form, &$form_state) {
  paragraphs_extra_include('ajax_api');
  paragraphs_extra_ajax_api_handle_command_submit($form, $form_state);
}


function paragraphs_extra_pretty_paragraphs_reload_submit($form, &$form_state) {
  paragraphs_extra_include('pretty_paragraphs');
  paragraphs_extra_pretty_paragraphs_handle_reload_submit($form, $form_state);
}

function paragraphs_extra_pretty_paragraphs_preview_rebuild_submit($form, &$form_state) {
  paragraphs_extra_include('pretty_paragraphs');
}

function paragraphs_extra_pretty_paragraphs_instance_settings_submit($form, &$form_state) {
  paragraphs_extra_include('pretty_paragraphs');
  paragraphs_extra_pretty_paragraphs_handle_instance_settings_submit($form, $form_state);
}

function paragraphs_extra_get_widget_wrapper_id($element, $context) {
  $wrapper_id = NULL;
  if ($context['field']['type'] == 'paragraphs') {
    if (preg_match('/id="([^"]+)"/', $element['#prefix'], $matches)) {
      $wrapper_id = $matches[1];
    }
  }
  return $wrapper_id;
}

function paragraphs_extra_include($type) {
  module_load_include('inc', 'paragraphs_extra', 'includes/paragraphs_extra.' . $type);
}

function _paragraphs_extra_id($namespace, $name = NULL) {
  $id = 'paragraphs_extra_' . $namespace;
  if ($name) {
    $id .= '_' . $name;
  }
  return drupal_html_id($id);
}

function _paragraphs_extra_class($namespace, $name = NULL) {
  $class = 'paragraphs-extra-' . $namespace;
  if ($name) {
    $class .= '-' . $name;
  }
  return $class;
}

function _paragraphs_extra_data($namespace, $name = NULL) {
  $data = 'data-paragraphs-extra-' . $namespace;
  if ($name) {
    $data .= '-' . $name;
  }
  return $data;
}

function _paragraphs_extra_vget($key, $default = NULL) {
  return variable_get('paragraphs_extra_' . $key, $default);
}

function _paragraphs_extra_vset($key, $value) {
  return variable_set('paragraphs_extra_' . $key, $value);
}
